version: '3.8'

services:
  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "80:80"
    networks:
      - object-storage-network
    depends_on:
      - server

  server:
    build:
      context: .
      dockerfile: build/server/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - object-storage-network
    depends_on:
      - postgres
      - storage-server

  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    networks:
      - object-storage-network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: meta-service

  storage-server:
    build:
      context: .
      dockerfile: build/storage-server/Dockerfile
    ports:
      - "50050-50070:50051"
    networks:
      - object-storage-network
    deploy:
      mode: replicated
      replicas: 6
      resources:
        limits:
          memory: 4G

networks:
  object-storage-network:
    driver: bridge